version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: sample_keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # The 'start-dev' command below uses an embedded H2 database by default.
      # If you want Keycloak to use your 'db' (PostgreSQL) service, uncomment and configure these:
      # KC_DB: postgres
      # KC_DB_URL_HOST: db
      # KC_DB_URL_DATABASE: keycloak_db # Ensure this database is created in your 'db' service
      # KC_DB_USERNAME: postgres # Or a dedicated Keycloak DB user
      # KC_DB_PASSWORD: password # The password for the Keycloak DB user
      # KC_SCHEMA: public
    ports:
      - '8180:8080'
    command: ['start-dev'] # Starts Keycloak in development mode. Not for production.
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    # depends_on:
    #  - db # Uncomment this if you configure Keycloak to use the 'db' service above

volumes:
  postgres-data-dev:
    driver: local